//! Contracts-root catalog access and generated-document persistence.

use std::ffi::OsStr;
use std::io::{ErrorKind, Write};
use std::path::{Path, PathBuf};

use atomic_write_file::AtomicWriteFile;
use conkit_signature::{CatalogPath, FileCatalog};
use walkdir::WalkDir;

use super::ownership::OwnershipManifest;
use super::path::{CatalogDirectory, ResolvedPath};
use super::reconciliation::{CatalogReconciliation, GenerationLock};
use crate::error::CliError;
use crate::platform::PortablePathRules;

/// Contracts-root access with generation-specific persistence capabilities.
#[derive(Debug)]
pub(crate) struct ContractsStore {
    directory: CatalogDirectory,
}

/// Policy for an existing destination that is not already owned.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ExistingOutputPolicy {
    /// Preserve every unowned destination and fail generation.
    Reject,
    /// Adopt a regular destination only when its bytes match generated bytes.
    AdoptMatching,
}

/// Completed generated documents and the exact catalog used to compute them.
#[derive(Debug)]
pub(crate) struct GeneratedContracts {
    baseline: FileCatalog,
    documents: FileCatalog,
}

/// Summary of filesystem reconciliation performed by one generation.
#[derive(Debug)]
pub(crate) struct GenerationReceipt {
    adopted_count: usize,
}

impl ContractsStore {
    /// Creates access to a contracts root without creating or validating it.
    pub(crate) fn new(path: PathBuf) -> Self {
        Self {
            directory: CatalogDirectory::contracts(path),
        }
    }

    /// Returns the selected contracts-root path.
    pub(crate) fn path(&self) -> &Path {
        self.directory.path()
    }

    /// Reads every non-metadata regular file from an existing contracts root.
    ///
    /// Entries are sorted by file name for deterministic catalog construction.
    /// The selected root may itself be a symlink to a directory; descendant
    /// symlinks are neither traversed nor inserted into the catalog.
    ///
    /// # Errors
    ///
    /// Returns an error if the root is not a directory, its reserved metadata
    /// namespace is invalid, walking or reading fails, a path is not portable,
    /// or duplicate logical paths are encountered.
    pub(crate) fn read(&self) -> Result<FileCatalog, CliError> {
        self.directory.validate_directory()?;
        self.validate_reserved_namespace()?;

        let mut catalog = FileCatalog::new();
        for entry in WalkDir::new(self.path())
            .follow_links(false)
            .sort_by_file_name()
        {
            let entry = entry?;
            if !entry.file_type().is_file() {
                continue;
            }

            let relative =
                entry
                    .path()
                    .strip_prefix(self.path())
                    .map_err(|_| CliError::PathOutsideRoot {
                        path: entry.path().to_path_buf(),
                    })?;
            if relative
                .components()
                .next()
                .is_some_and(|component| component.as_os_str() == OwnershipManifest::DIRECTORY)
            {
                continue;
            }

            let logical = self.directory.logical_path(entry.path())?;
            catalog.insert(logical, fs_err::read(entry.path())?)?;
        }

        Ok(catalog)
    }

    /// Reads an existing contracts root or returns an empty generation catalog
    /// when the selected path is lexically absent.
    ///
    /// # Errors
    ///
    /// Returns an error if an existing root cannot be inspected or read,
    /// including when it is a file, dangling symlink, or contains an invalid
    /// reserved metadata namespace.
    pub(crate) fn read_optional(&self) -> Result<FileCatalog, CliError> {
        match fs_err::symlink_metadata(self.path()) {
            Ok(_) => self.read(),
            Err(source) if source.kind() == ErrorKind::NotFound => Ok(FileCatalog::new()),
            Err(source) => Err(CliError::Io(source)),
        }
    }

    /// Reconciles generated documents and their ownership metadata.
    ///
    /// # Errors
    ///
    /// Returns an error when locking, recovery, baseline validation, preflight,
    /// reservation, mutation, rollback, verification, or ownership persistence
    /// fails.
    pub(crate) fn write_generated(
        &self,
        generated: GeneratedContracts,
        policy: ExistingOutputPolicy,
    ) -> Result<GenerationReceipt, CliError> {
        CatalogReconciliation::new(self, generated, policy)?.apply()
    }

    /// Validates the reserved metadata directory and every recognized entry.
    pub(super) fn validate_reserved_namespace(&self) -> Result<(), CliError> {
        let entries = match fs_err::read_dir(self.path()) {
            Ok(entries) => entries,
            Err(source) if source.kind() == ErrorKind::NotFound => return Ok(()),
            Err(source) => return Err(CliError::Io(source)),
        };
        let mut metadata_directory = None;

        for entry in entries {
            let entry = entry?;
            let name = entry.file_name();
            if name.eq_ignore_ascii_case(OwnershipManifest::DIRECTORY) {
                if name != OwnershipManifest::DIRECTORY || metadata_directory.is_some() {
                    return Err(CliError::ReservedMetadataEntry { path: entry.path() });
                }
                metadata_directory = Some(entry.path());
            }
        }

        let Some(directory) = metadata_directory else {
            return Ok(());
        };
        let metadata = fs_err::symlink_metadata(&directory)?;
        if !metadata.file_type().is_dir() || metadata.file_type().is_symlink() {
            return Err(CliError::ReservedMetadataEntry { path: directory });
        }

        for entry in fs_err::read_dir(&directory)? {
            let entry = entry?;
            let name = entry.file_name();
            if (name != OwnershipManifest::FILE_NAME
                && name != GenerationLock::FILE_NAME
                && !Self::is_manifest_atomic_temporary_name(&name))
                || !entry.file_type()?.is_file()
            {
                return Err(CliError::ReservedMetadataEntry { path: entry.path() });
            }
        }

        Ok(())
    }

    /// Removes only recognized abandoned atomic ownership-manifest writes.
    pub(super) fn remove_abandoned_manifest_temporaries(&self) -> Result<(), CliError> {
        let directory = self.path().join(OwnershipManifest::DIRECTORY);
        let entries = match fs_err::read_dir(&directory) {
            Ok(entries) => entries,
            Err(source) if source.kind() == ErrorKind::NotFound => return Ok(()),
            Err(source) => return Err(CliError::Io(source)),
        };

        for entry in entries {
            let entry = entry?;
            if Self::is_manifest_atomic_temporary_name(&entry.file_name()) {
                if !entry.file_type()?.is_file() {
                    return Err(CliError::ReservedMetadataEntry { path: entry.path() });
                }
                fs_err::remove_file(entry.path())?;
            }
        }

        Ok(())
    }

    /// Maps one logical catalog path below the selected contracts root.
    fn output_path_for(&self, logical: &CatalogPath) -> Result<PathBuf, CliError> {
        let mut path = self.path().to_path_buf();
        for component in logical.as_str().split('/') {
            PortablePathRules::validate_component(OsStr::new(component))?;
            path.push(component);
        }
        Ok(path)
    }

    /// Maps and containment-checks one generated logical path.
    pub(super) fn validated_output_path(
        &self,
        root: &ResolvedPath,
        logical: &CatalogPath,
    ) -> Result<PathBuf, CliError> {
        if logical
            .as_str()
            .split('/')
            .next()
            .is_some_and(|component| component.eq_ignore_ascii_case(OwnershipManifest::DIRECTORY))
        {
            return Err(CliError::ReservedMetadataEntry {
                path: self.output_path_for(logical)?,
            });
        }

        let output = self.output_path_for(logical)?;
        root.ensure_generated_path(&output)?;
        Ok(output)
    }

    /// Writes one file through an individually atomic replacement.
    pub(super) fn atomic_write(
        &self,
        root: &ResolvedPath,
        path: &Path,
        bytes: &[u8],
    ) -> Result<(), CliError> {
        root.ensure_generated_path(path)?;
        if let Some(parent) = path.parent() {
            fs_err::create_dir_all(parent)?;
        }

        let mut output = AtomicWriteFile::open(path)?;
        output.write_all(bytes)?;
        output.commit()?;
        Ok(())
    }

    fn is_manifest_atomic_temporary_name(name: &OsStr) -> bool {
        name.to_str()
            .and_then(|name| name.strip_prefix(OwnershipManifest::TEMPORARY_PREFIX))
            .is_some_and(|suffix| {
                suffix.len() == OwnershipManifest::ATOMIC_TEMPORARY_SUFFIX_LENGTH
                    && suffix.bytes().all(|byte| byte.is_ascii_alphanumeric())
            })
    }
}

impl GeneratedContracts {
    /// Binds completed generated documents to the exact input snapshot.
    pub(crate) fn new(baseline: FileCatalog, documents: FileCatalog) -> Self {
        Self {
            baseline,
            documents,
        }
    }

    /// Consumes the completed result into its baseline and output catalog.
    pub(super) fn into_parts(self) -> (FileCatalog, FileCatalog) {
        (self.baseline, self.documents)
    }
}

impl GenerationReceipt {
    /// Creates a receipt after successful reconciliation.
    pub(super) fn new(adopted_count: usize) -> Self {
        Self { adopted_count }
    }

    /// Returns the number of matching pre-existing files adopted by this run.
    pub(crate) fn adopted_count(self) -> usize {
        self.adopted_count
    }
}

#[cfg(test)]
mod tests {
    use assert_fs::prelude::*;
    use conkit_signature::{CatalogPath, FileCatalog};

    use super::{ContractsStore, GeneratedContracts};
    use crate::catalog::{PathRole, ResolvedPath};

    #[test]
    fn required_and_optional_reads_distinguish_missing_directory_and_file_roots() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let missing = temp.child("missing");
        let store = ContractsStore::new(missing.path().to_path_buf());
        assert!(store.read().is_err(), "required root must exist");
        assert!(
            store
                .read_optional()
                .expect("missing generation root")
                .is_empty()
        );

        let directory = temp.child("contracts");
        directory.create_dir_all().expect("contracts root");
        directory
            .child("nested")
            .create_dir_all()
            .expect("nested contracts directory");
        directory
            .child("nested/manual.txt")
            .write_str("manual\n")
            .expect("contract entry");
        directory
            .child("main.yml")
            .write_str("root: ../src\n")
            .expect("combined document");
        let catalog = ContractsStore::new(directory.path().to_path_buf())
            .read_optional()
            .expect("existing root");
        assert_eq!(catalog.len(), 2, "all non-metadata files are retained");

        let file = temp.child("contracts-file");
        file.touch().expect("non-directory root");
        let error = ContractsStore::new(file.path().to_path_buf())
            .read_optional()
            .expect_err("file root");
        assert!(error.to_string().contains("is not a directory"));
        temp.close().expect("close temporary root");
    }

    #[test]
    fn contract_reads_exclude_only_valid_reserved_metadata() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts
            .child(".contract-kit")
            .create_dir_all()
            .expect("metadata directory");
        contracts
            .child(".contract-kit/generated-files.json")
            .write_str("{}\n")
            .expect("recognized manifest");
        contracts
            .child(".contract-kit/generation.lock")
            .touch()
            .expect("recognized lock");
        contracts
            .child("main.yml")
            .write_str("root: ../src\n")
            .expect("combined document");
        contracts
            .child(".contract-kitty")
            .create_dir_all()
            .expect("similarly named user directory");
        contracts
            .child(".contract-kitty/manual.txt")
            .write_str("manual\n")
            .expect("similarly named user directory");

        let catalog = ContractsStore::new(contracts.path().to_path_buf())
            .read()
            .expect("contracts catalog");
        assert_eq!(catalog.len(), 2);
        assert!(
            catalog
                .get(&CatalogPath::new("main.yml").expect("document path"))
                .is_some()
        );
        assert!(
            catalog
                .get(&CatalogPath::new(".contract-kitty/manual.txt").expect("manual path"))
                .is_some()
        );

        contracts
            .child(".contract-kit/unknown")
            .touch()
            .expect("unknown metadata entry");
        assert!(
            ContractsStore::new(contracts.path().to_path_buf())
                .read()
                .is_err(),
            "unknown reserved entries must fail before walking"
        );
        temp.close().expect("close temporary root");
    }

    #[test]
    fn recognized_manifest_temporaries_are_removed_without_touching_other_entries() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        let metadata = contracts.child(".contract-kit");
        metadata.create_dir_all().expect("metadata directory");
        let recognized = metadata.child(".generated-files.json.a1B2c3");
        recognized.touch().expect("recognized temporary");
        let manifest = metadata.child("generated-files.json");
        manifest.touch().expect("manifest");

        let store = ContractsStore::new(contracts.path().to_path_buf());
        store
            .validate_reserved_namespace()
            .expect("valid namespace");
        let unrecognized = metadata.child(".generated-files.json.short");
        unrecognized
            .touch()
            .expect("unrecognized temporary-shaped entry");
        store
            .remove_abandoned_manifest_temporaries()
            .expect("temporary cleanup");

        recognized.assert(predicates::path::missing());
        unrecognized.assert(predicates::path::exists());
        manifest.assert(predicates::path::exists());
        temp.close().expect("close temporary root");
    }

    #[test]
    fn maps_and_atomically_writes_generated_output_below_the_root() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts.create_dir_all().expect("contracts root");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let root = ResolvedPath::new(PathRole::Contracts, contracts.path().to_path_buf())
            .expect("resolved root");
        let logical = CatalogPath::new("nested/main.yaml").expect("logical path");
        let destination = store
            .validated_output_path(&root, &logical)
            .expect("validated destination");

        store
            .atomic_write(&root, &destination, b"version: 1\n")
            .expect("atomic output");

        contracts.child("nested/main.yaml").assert("version: 1\n");
        let reserved = CatalogPath::new(".CONTRACT-KIT/output.yml").expect("reserved path");
        assert!(store.validated_output_path(&root, &reserved).is_err());
        let outside = temp.child("outside.yml");
        assert!(
            store
                .atomic_write(&root, outside.path(), b"outside\n")
                .is_err()
        );
        outside.assert(predicates::path::missing());
        temp.close().expect("close temporary root");
    }

    #[cfg(unix)]
    #[test]
    fn contract_reads_do_not_follow_or_insert_descendant_symlinks() {
        use std::os::unix::fs::symlink;

        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        let outside = temp.child("outside");
        contracts.create_dir_all().expect("contracts root");
        outside.create_dir_all().expect("outside root");
        contracts
            .child("main.yml")
            .write_str("root: ../src\n")
            .expect("contract document");
        outside
            .child("secret.yml")
            .write_str("outside\n")
            .expect("outside file");
        symlink(outside.path(), contracts.child("linked-directory").path())
            .expect("directory symlink");
        symlink(
            outside.child("secret.yml").path(),
            contracts.child("linked-file.yml").path(),
        )
        .expect("file symlink");

        let catalog = ContractsStore::new(contracts.path().to_path_buf())
            .read()
            .expect("contracts catalog");

        assert_eq!(catalog.len(), 1);
        assert!(
            catalog
                .get(&CatalogPath::new("main.yml").expect("document path"))
                .is_some()
        );
        temp.close().expect("close temporary root");
    }

    #[cfg(unix)]
    #[test]
    fn optional_read_accepts_a_directory_root_symlink_but_not_a_dangling_symlink() {
        use std::os::unix::fs::symlink;

        let temp = assert_fs::TempDir::new().expect("temporary root");
        let actual = temp.child("actual");
        actual.create_dir_all().expect("actual contracts root");
        actual
            .child("main.yml")
            .write_str("root: ../src\n")
            .expect("contract entry");
        let selected = temp.child("selected");
        symlink(actual.path(), selected.path()).expect("directory root symlink");
        assert_eq!(
            ContractsStore::new(selected.path().to_path_buf())
                .read_optional()
                .expect("directory root symlink")
                .len(),
            1
        );

        let dangling = temp.child("dangling");
        symlink(temp.child("absent").path(), dangling.path()).expect("dangling root symlink");
        assert!(
            ContractsStore::new(dangling.path().to_path_buf())
                .read_optional()
                .is_err(),
            "only a lexically absent root is optional"
        );
        temp.close().expect("close temporary root");
    }

    #[test]
    fn generated_contracts_move_the_baseline_and_completed_documents() {
        let baseline_path = CatalogPath::new("before.yml").expect("baseline path");
        let document_path = CatalogPath::new("main.yml").expect("document path");
        let mut baseline = FileCatalog::new();
        baseline
            .insert(baseline_path.clone(), b"before\n".to_vec())
            .expect("baseline insert");
        let mut documents = FileCatalog::new();
        documents
            .insert(document_path.clone(), b"after\n".to_vec())
            .expect("document insert");

        let (baseline, documents) = GeneratedContracts::new(baseline, documents).into_parts();

        assert_eq!(baseline.get(&baseline_path), Some(b"before\n".as_slice()));
        assert_eq!(documents.get(&document_path), Some(b"after\n".as_slice()));
    }
}
