//! Contracts-root catalog access and generated-document persistence.

use std::ffi::OsStr;
use std::io::{ErrorKind, Write};
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use cap_fs_ext::{DirExt as _, FollowSymlinks, OpenOptionsFollowExt as _};
use cap_std::fs::{Dir, File, OpenOptions};
use conkit_signature::{CatalogPath, FileCatalog};

use super::ownership::OwnershipManifest;
use super::path::{CatalogDirectory, CatalogLeaf, PathRole};
use super::reconciliation::{CatalogReconciliation, GenerationLock};
use super::{CatalogReadBudget, CatalogReadLimits};
use crate::error::CliError;
use crate::platform::PortablePathRules;

/// Contracts-root access with generation-specific persistence capabilities.
#[derive(Debug)]
pub(crate) struct ContractsStore {
    directory: CatalogDirectory,
    limits: CatalogReadLimits,
}

/// Bytes and stable identity obtained from one capability-opened file handle.
#[derive(Debug)]
pub(super) struct FileSnapshot {
    bytes: Vec<u8>,
    identity: same_file::Handle,
}

/// Policy for an existing destination that is not already owned.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ExistingOutputPolicy {
    /// Preserve every unowned destination and fail generation.
    Reject,
    /// Adopt a regular destination only when its bytes match generated bytes.
    AdoptMatching,
}

/// Completed generated documents and the exact catalog used to compute them.
#[derive(Debug)]
pub(crate) struct GeneratedContracts {
    baseline: FileCatalog,
    documents: FileCatalog,
}

/// Summary of filesystem reconciliation performed by one generation.
#[derive(Debug)]
pub(crate) struct GenerationReceipt {
    adopted_count: usize,
}

struct ContractPublication<'destination> {
    temporary: std::ffi::OsString,
    destination: &'destination CatalogLeaf,
    state: ContractPublicationState,
}

enum ContractPublicationState {
    Writing(File),
    Prepared,
    Published,
    Aborted,
}

impl<'destination> ContractPublication<'destination> {
    fn create(
        destination: &'destination CatalogLeaf,
        cancellation: &crate::context::ApplicationCancellation,
    ) -> Result<Self, CliError> {
        cancellation.checkpoint()?;
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|duration| duration.as_nanos())
            .unwrap_or_default();

        for attempt in 0_u16..=u16::MAX {
            cancellation.checkpoint()?;
            let temporary = Self::temporary_name(destination.name(), timestamp, attempt);
            match Self::open(destination, temporary) {
                Ok(publication) => return Ok(publication),
                Err(CliError::Io(source)) if source.kind() == ErrorKind::AlreadyExists => {}
                Err(source) => return Err(source),
            }
        }

        Err(CliError::Io(std::io::Error::new(
            ErrorKind::AlreadyExists,
            format!(
                "no collision-free atomic temporary name is available for {}",
                destination.display_path().display()
            ),
        )))
    }

    fn open(
        destination: &'destination CatalogLeaf,
        temporary: std::ffi::OsString,
    ) -> Result<Self, CliError> {
        let mut options = OpenOptions::new();
        options
            .write(true)
            .create_new(true)
            .follow(FollowSymlinks::No);
        let output = destination.open_sibling(&temporary, &options)?;
        Ok(Self {
            temporary,
            destination,
            state: ContractPublicationState::Writing(output),
        })
    }

    fn publish(
        mut self,
        bytes: &[u8],
        cancellation: &crate::context::ApplicationCancellation,
    ) -> Result<(), CliError> {
        if let Err(operation) = self.write_and_prepare(bytes, cancellation) {
            return Err(self.abort(operation));
        }
        if let Err(canceled) = cancellation.checkpoint() {
            return Err(self.abort(canceled));
        }
        if let Err(operation) = self.destination.rename_sibling(&self.temporary) {
            return Err(self.abort(operation));
        }
        self.state = ContractPublicationState::Published;
        self.destination.sync_parent()
    }

    fn write_and_prepare(
        &mut self,
        bytes: &[u8],
        cancellation: &crate::context::ApplicationCancellation,
    ) -> Result<(), CliError> {
        for chunk in bytes.chunks(64 * 1024) {
            cancellation.checkpoint()?;
            self.output()?.write_all(chunk)?;
        }
        cancellation.checkpoint()?;
        self.output()?.flush()?;
        self.output()?.sync_all()?;
        self.close();
        Ok(())
    }

    fn output(&mut self) -> Result<&mut File, std::io::Error> {
        match &mut self.state {
            ContractPublicationState::Writing(output) => Ok(output),
            ContractPublicationState::Prepared
            | ContractPublicationState::Published
            | ContractPublicationState::Aborted => Err(std::io::Error::other(
                "atomic contract publication is no longer writable",
            )),
        }
    }

    fn close(&mut self) {
        if matches!(&self.state, ContractPublicationState::Writing(_)) {
            self.state = ContractPublicationState::Prepared;
        }
    }

    fn abort(mut self, operation: CliError) -> CliError {
        self.close();
        let cleanup = self.destination.remove_sibling(&self.temporary);
        self.state = ContractPublicationState::Aborted;
        match cleanup {
            Ok(()) => operation,
            Err(cleanup) if cleanup.kind() == ErrorKind::NotFound => operation,
            Err(cleanup) => Self::cleanup_failure(operation, cleanup),
        }
    }

    fn cleanup_failure(operation: CliError, cleanup: std::io::Error) -> CliError {
        match operation {
            CliError::OperationCanceled => CliError::Io(std::io::Error::new(
                cleanup.kind(),
                format!("operation canceled; atomic temporary cleanup also failed: {cleanup}"),
            )),
            CliError::Io(operation) => CliError::Io(std::io::Error::new(
                operation.kind(),
                format!("{operation}; atomic temporary cleanup also failed: {cleanup}"),
            )),
            operation => CliError::Io(std::io::Error::new(
                cleanup.kind(),
                format!("{operation}; atomic temporary cleanup also failed: {cleanup}"),
            )),
        }
    }

    fn temporary_name(destination: &OsStr, timestamp: u128, attempt: u16) -> std::ffi::OsString {
        if destination == OwnershipManifest::FILE_NAME {
            let suffix = (timestamp as u64)
                .wrapping_add(u64::from(std::process::id()) << 16)
                .wrapping_add(u64::from(attempt))
                & 0xff_ffff;
            return format!("{}{:06x}", OwnershipManifest::TEMPORARY_PREFIX, suffix).into();
        }

        format!(
            ".contract-kit-{}-{timestamp}-{attempt}.tmp",
            std::process::id()
        )
        .into()
    }
}

impl Drop for ContractPublication<'_> {
    fn drop(&mut self) {
        if matches!(
            &self.state,
            ContractPublicationState::Writing(_) | ContractPublicationState::Prepared
        ) {
            self.close();
            let _ = self.destination.remove_sibling(&self.temporary);
            self.state = ContractPublicationState::Aborted;
        }
    }
}

impl ContractsStore {
    /// Creates access to a contracts root without creating or validating it.
    pub(crate) fn new(path: PathBuf) -> Self {
        Self {
            directory: CatalogDirectory::contracts(path),
            limits: CatalogReadLimits::default(),
        }
    }

    /// Replaces the filesystem catalog budgets for this contracts root.
    pub(crate) fn with_limits(mut self, limits: CatalogReadLimits) -> Self {
        self.limits = limits;
        self
    }

    /// Returns the selected contracts-root path.
    pub(crate) fn path(&self) -> &Path {
        self.directory.path()
    }

    /// Reads the required contracts catalog against a caller-owned operation budget.
    pub(crate) fn read_with_budget(
        &self,
        budget: &mut CatalogReadBudget,
    ) -> Result<FileCatalog, CliError> {
        let root = self.directory.capability()?;
        self.validate_reserved_namespace_with_budget(budget)?;

        let mut catalog = FileCatalog::new();
        self.read_contract_directory(&root, Path::new(""), budget, &mut catalog)?;

        Ok(catalog)
    }

    fn read_contract_directory(
        &self,
        directory: &Dir,
        relative: &Path,
        budget: &mut CatalogReadBudget,
        catalog: &mut FileCatalog,
    ) -> Result<(), CliError> {
        for entry in self.directory.sorted_entries(directory, relative, budget)? {
            budget.checkpoint()?;
            let name = entry.file_name();
            if relative.as_os_str().is_empty() && name == OwnershipManifest::DIRECTORY {
                continue;
            }
            let file_type = entry.file_type()?;
            if file_type.is_symlink() {
                continue;
            }
            if file_type.is_dir() {
                let child = self
                    .directory
                    .open_directory_child(directory, &name, relative)?;
                let child_relative = relative.join(&name);
                self.read_contract_directory(&child, &child_relative, budget, catalog)?;
                continue;
            }
            if !file_type.is_file() {
                continue;
            }

            let entry_relative = relative.join(&name);
            let physical = self.path().join(&entry_relative);
            budget.begin_entry(&physical)?;
            let logical = self.directory.logical_path(&physical)?;
            let leaf = self.directory.discovered_leaf(directory, &name, relative)?;
            let mut file = leaf
                .open_regular()?
                .ok_or_else(|| CliError::Io(std::io::ErrorKind::NotFound.into()))?;
            budget.preflight_file(&physical, file.metadata()?.len())?;
            let bytes = budget.read_file(&physical, &mut file)?;
            catalog.insert(logical, bytes)?;
        }
        Ok(())
    }

    /// Reads the optional contracts catalog against a caller-owned operation budget.
    pub(crate) fn read_optional_with_budget(
        &self,
        budget: &mut CatalogReadBudget,
    ) -> Result<FileCatalog, CliError> {
        if self.directory.is_lexically_absent()? {
            Ok(FileCatalog::new())
        } else {
            self.read_with_budget(budget)
        }
    }

    /// Reconciles generated documents against the caller's complete operation ledger.
    pub(crate) fn write_generated_with_budget(
        &self,
        generated: GeneratedContracts,
        policy: ExistingOutputPolicy,
        budget: CatalogReadBudget,
    ) -> Result<GenerationReceipt, CliError> {
        CatalogReconciliation::new(self, generated, policy, budget)?.apply()
    }

    pub(super) fn validate_reserved_namespace_with_budget(
        &self,
        budget: &mut CatalogReadBudget,
    ) -> Result<(), CliError> {
        budget.checkpoint()?;
        if self.directory.is_lexically_absent()? {
            return Ok(());
        }
        let root = self.directory.capability()?;
        let mut metadata_directory = None::<std::ffi::OsString>;

        for entry in root.entries()? {
            budget.checkpoint()?;
            budget.visit_traversal_entry(self.path())?;
            let entry = entry?;
            let name = entry.file_name();
            if name.eq_ignore_ascii_case(OwnershipManifest::DIRECTORY) {
                if name != OwnershipManifest::DIRECTORY || metadata_directory.is_some() {
                    return Err(CliError::ReservedMetadataEntry {
                        path: self.path().join(name),
                    });
                }
                metadata_directory = Some(name);
            }
        }

        let Some(directory_name) = metadata_directory else {
            return Ok(());
        };
        let metadata = root.symlink_metadata(&directory_name)?;
        if !metadata.is_dir() || metadata.file_type().is_symlink() {
            return Err(CliError::ReservedMetadataEntry {
                path: self.path().join(&directory_name),
            });
        }
        let directory = root.open_dir_nofollow(&directory_name)?;

        for entry in directory.entries()? {
            budget.checkpoint()?;
            budget.visit_traversal_entry(&self.path().join(OwnershipManifest::DIRECTORY))?;
            let entry = entry?;
            let name = entry.file_name();
            if (name != OwnershipManifest::FILE_NAME
                && name != GenerationLock::FILE_NAME
                && !Self::is_manifest_atomic_temporary_name(&name))
                || !entry.file_type()?.is_file()
            {
                return Err(CliError::ReservedMetadataEntry {
                    path: self.path().join(OwnershipManifest::DIRECTORY).join(name),
                });
            }
        }

        Ok(())
    }

    pub(super) fn remove_abandoned_manifest_temporaries_with_budget(
        &self,
        budget: &mut CatalogReadBudget,
    ) -> Result<(), CliError> {
        budget.checkpoint()?;
        if self.directory.is_lexically_absent()? {
            return Ok(());
        }
        let root = self.directory.capability()?;
        let metadata_name = OsStr::new(OwnershipManifest::DIRECTORY);
        let metadata = match root.symlink_metadata(metadata_name) {
            Ok(metadata) => metadata,
            Err(source) if source.kind() == ErrorKind::NotFound => return Ok(()),
            Err(source) => return Err(CliError::Io(source)),
        };
        if metadata.file_type().is_symlink() || !metadata.is_dir() {
            return Err(CliError::ReservedMetadataEntry {
                path: self.path().join(metadata_name),
            });
        }
        let directory = root.open_dir_nofollow(metadata_name)?;

        for entry in directory.entries()? {
            budget.checkpoint()?;
            budget.visit_traversal_entry(&self.path().join(OwnershipManifest::DIRECTORY))?;
            let entry = entry?;
            let name = entry.file_name();
            if Self::is_manifest_atomic_temporary_name(&name) {
                if !entry.file_type()?.is_file() {
                    return Err(CliError::ReservedMetadataEntry {
                        path: self.path().join(metadata_name).join(&name),
                    });
                }
                directory.remove_file(&name)?;
            }
        }

        Ok(())
    }

    /// Starts one cumulative budget for reconciliation-owned metadata and
    /// generated-output reads.
    pub(super) fn begin_reconciliation_read(
        &self,
        cancellation: &crate::context::ApplicationCancellation,
    ) -> CatalogReadBudget {
        self.limits.begin(cancellation)
    }

    /// Resolves the existing ownership-manifest name without creating the
    /// selected root or reserved metadata directory.
    pub(super) fn existing_ownership_leaf(&self) -> Result<Option<CatalogLeaf>, CliError> {
        if self.directory.is_lexically_absent()? {
            return Ok(None);
        }
        let relative = Path::new(OwnershipManifest::DIRECTORY).join(OwnershipManifest::FILE_NAME);
        match self
            .directory
            .existing_leaf(&relative, PathRole::GeneratedOutput)
        {
            Ok(leaf) => Ok(Some(leaf)),
            Err(CliError::Io(source)) if source.kind() == ErrorKind::NotFound => Ok(None),
            Err(error) => Err(error),
        }
    }

    /// Resolves the ownership-manifest name and creates its anchored metadata
    /// parent when persistence is required.
    pub(super) fn ownership_leaf_for_write(&self) -> Result<CatalogLeaf, CliError> {
        let relative = Path::new(OwnershipManifest::DIRECTORY).join(OwnershipManifest::FILE_NAME);
        self.directory
            .create_leaf(&relative, PathRole::GeneratedOutput)
    }

    /// Resolves the capability-relative generation-lock name.
    pub(super) fn generation_lock_leaf(&self) -> Result<CatalogLeaf, CliError> {
        let relative = Path::new(OwnershipManifest::DIRECTORY).join(GenerationLock::FILE_NAME);
        self.directory
            .create_leaf(&relative, PathRole::GeneratedOutput)
    }

    /// Maps one logical catalog path to a portable relative filesystem path.
    fn output_relative_for(&self, logical: &CatalogPath) -> Result<PathBuf, CliError> {
        let mut path = PathBuf::new();
        for component in logical.as_str().split('/') {
            PortablePathRules::validate_component(OsStr::new(component))?;
            path.push(component);
        }
        Ok(path)
    }

    /// Binds one generated logical path to the retained contracts capability.
    ///
    /// # Errors
    ///
    /// Returns an error if the logical path enters the reserved namespace, has
    /// a nonportable component, encounters a symlink, or escapes the contracts
    /// root.
    pub(super) fn generated_leaf(&self, logical: &CatalogPath) -> Result<CatalogLeaf, CliError> {
        if logical
            .as_str()
            .split('/')
            .next()
            .is_some_and(|component| component.eq_ignore_ascii_case(OwnershipManifest::DIRECTORY))
        {
            return Err(CliError::ReservedMetadataEntry {
                path: self.path().join(self.output_relative_for(logical)?),
            });
        }

        let relative = self.output_relative_for(logical)?;
        self.directory
            .create_leaf(&relative, PathRole::GeneratedOutput)
    }

    /// Reads one anchored regular file under the cumulative reconciliation
    /// budget and derives alias identity from a clone of that same opened
    /// handle. Metadata length is only an early check; the actual read is
    /// capped at the remaining limit plus one evidence byte.
    pub(super) fn read_leaf(
        &self,
        leaf: &CatalogLeaf,
        budget: &mut CatalogReadBudget,
    ) -> Result<Option<FileSnapshot>, CliError> {
        budget.begin_entry(leaf.display_path())?;
        let mut file = match leaf.open_regular() {
            Ok(Some(file)) => file,
            Ok(None) => return Ok(None),
            Err(CliError::Io(source)) if source.kind() == ErrorKind::NotFound => return Ok(None),
            Err(error) => return Err(error),
        };
        budget.preflight_file(leaf.display_path(), file.metadata()?.len())?;
        let identity = same_file::Handle::from_file(file.try_clone()?.into_std())?;
        let bytes = budget.read_file(leaf.display_path(), &mut file)?;
        Ok(Some(FileSnapshot { bytes, identity }))
    }

    /// Writes one file through an individually atomic replacement.
    ///
    /// # Errors
    ///
    /// Returns an error if containment or symlink validation fails, parent
    /// creation fails, or the atomic file cannot be opened, written, or
    /// committed. Cancellation is observed through the last checkpoint before
    /// the destination rename. Once publication begins, the rename and parent
    /// synchronization result is definitive and cannot be replaced by a late
    /// cancellation request.
    pub(super) fn atomic_write(
        &self,
        destination: &CatalogLeaf,
        bytes: &[u8],
        cancellation: &crate::context::ApplicationCancellation,
    ) -> Result<(), CliError> {
        ContractPublication::create(destination, cancellation)?.publish(bytes, cancellation)
    }

    fn is_manifest_atomic_temporary_name(name: &OsStr) -> bool {
        name.to_str()
            .and_then(|name| name.strip_prefix(OwnershipManifest::TEMPORARY_PREFIX))
            .is_some_and(|suffix| {
                suffix.len() == OwnershipManifest::ATOMIC_TEMPORARY_SUFFIX_LENGTH
                    && suffix.bytes().all(|byte| byte.is_ascii_alphanumeric())
            })
    }
}

impl FileSnapshot {
    /// Returns bytes read through the opened capability handle.
    pub(super) fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Consumes the snapshot and returns identity derived from that same
    /// opened handle.
    pub(super) fn into_identity(self) -> same_file::Handle {
        self.identity
    }
}

impl GeneratedContracts {
    /// Binds completed generated documents to the exact input snapshot.
    pub(crate) fn new(baseline: FileCatalog, documents: FileCatalog) -> Self {
        Self {
            baseline,
            documents,
        }
    }

    /// Consumes the completed result into its baseline and output catalog.
    pub(super) fn into_parts(self) -> (FileCatalog, FileCatalog) {
        (self.baseline, self.documents)
    }
}

impl GenerationReceipt {
    /// Creates a receipt after successful reconciliation.
    pub(super) fn new(adopted_count: usize) -> Self {
        Self { adopted_count }
    }

    /// Returns the number of matching pre-existing files adopted by this run.
    pub(crate) fn adopted_count(self) -> usize {
        self.adopted_count
    }
}

#[cfg(test)]
mod tests {
    use assert_fs::prelude::*;
    use conkit_signature::{CatalogPath, FileCatalog};

    use super::{ContractPublication, ContractsStore, GeneratedContracts, OwnershipManifest};
    use crate::catalog::{CatalogReadLimitResource, CatalogReadLimits};
    use crate::error::CliError;

    #[test]
    fn required_and_optional_reads_distinguish_missing_directory_and_file_roots() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let missing = temp.child("missing");
        let store = ContractsStore::new(missing.path().to_path_buf());
        let cancellation = crate::context::ApplicationCancellation::new();
        let mut required_budget = store.limits.begin(&cancellation);
        assert!(
            store.read_with_budget(&mut required_budget).is_err(),
            "required root must exist"
        );
        let mut optional_budget = store.limits.begin(&cancellation);
        assert!(
            store
                .read_optional_with_budget(&mut optional_budget)
                .expect("missing generation root")
                .is_empty()
        );

        let directory = temp.child("contracts");
        directory.create_dir_all().expect("contracts root");
        directory
            .child("nested")
            .create_dir_all()
            .expect("nested contracts directory");
        directory
            .child("nested/manual.txt")
            .write_str("manual\n")
            .expect("contract entry");
        directory
            .child("main.yml")
            .write_str("root: ../src\n")
            .expect("combined document");
        let store = ContractsStore::new(directory.path().to_path_buf());
        let mut budget = store.limits.begin(&cancellation);
        let catalog = store
            .read_optional_with_budget(&mut budget)
            .expect("existing root");
        assert_eq!(catalog.len(), 2, "all non-metadata files are retained");

        let file = temp.child("contracts-file");
        file.touch().expect("non-directory root");
        let store = ContractsStore::new(file.path().to_path_buf());
        let mut budget = store.limits.begin(&cancellation);
        let error = store
            .read_optional_with_budget(&mut budget)
            .expect_err("file root");
        assert!(error.to_string().contains("is not a directory"));
        temp.close().expect("close temporary root");
    }

    #[test]
    fn contract_reads_exclude_only_valid_reserved_metadata() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts
            .child(".contract-kit")
            .create_dir_all()
            .expect("metadata directory");
        contracts
            .child(".contract-kit/generated-files.json")
            .write_str("{}\n")
            .expect("recognized manifest");
        contracts
            .child(".contract-kit/generation.lock")
            .touch()
            .expect("recognized lock");
        contracts
            .child("main.yml")
            .write_str("root: ../src\n")
            .expect("combined document");
        contracts
            .child(".contract-kitty")
            .create_dir_all()
            .expect("similarly named user directory");
        contracts
            .child(".contract-kitty/manual.txt")
            .write_str("manual\n")
            .expect("similarly named user directory");

        let store = ContractsStore::new(contracts.path().to_path_buf());
        let cancellation = crate::context::ApplicationCancellation::new();
        let mut budget = store.limits.begin(&cancellation);
        let catalog = store
            .read_with_budget(&mut budget)
            .expect("contracts catalog");
        assert_eq!(catalog.len(), 2);
        assert!(
            catalog
                .get(&CatalogPath::new("main.yml").expect("document path"))
                .is_some()
        );
        assert!(
            catalog
                .get(&CatalogPath::new(".contract-kitty/manual.txt").expect("manual path"))
                .is_some()
        );

        contracts
            .child(".contract-kit/unknown")
            .touch()
            .expect("unknown metadata entry");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let mut budget = store.limits.begin(&cancellation);
        assert!(
            store.read_with_budget(&mut budget).is_err(),
            "unknown reserved entries must fail before walking"
        );
        temp.close().expect("close temporary root");
    }

    #[test]
    fn recognized_manifest_temporaries_are_removed_without_touching_other_entries() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        let metadata = contracts.child(".contract-kit");
        metadata.create_dir_all().expect("metadata directory");
        let recognized = metadata.child(".generated-files.json.a1B2c3");
        recognized.touch().expect("recognized temporary");
        let manifest = metadata.child("generated-files.json");
        manifest.touch().expect("manifest");

        let store = ContractsStore::new(contracts.path().to_path_buf());
        let cancellation = crate::context::ApplicationCancellation::new();
        let mut budget = store.limits.begin(&cancellation);
        store
            .validate_reserved_namespace_with_budget(&mut budget)
            .expect("valid namespace");
        let unrecognized = metadata.child(".generated-files.json.short");
        unrecognized
            .touch()
            .expect("unrecognized temporary-shaped entry");
        store
            .remove_abandoned_manifest_temporaries_with_budget(&mut budget)
            .expect("temporary cleanup");

        recognized.assert(predicates::path::missing());
        unrecognized.assert(predicates::path::exists());
        manifest.assert(predicates::path::exists());
        drop(store);
        temp.close().expect("close temporary root");
    }

    #[test]
    fn manifest_atomic_temporary_names_remain_cleanup_compatible() {
        let manifest = ContractPublication::temporary_name(
            std::ffi::OsStr::new(OwnershipManifest::FILE_NAME),
            0x12_3456,
            0,
        );
        let contract =
            ContractPublication::temporary_name(std::ffi::OsStr::new("main.yml"), 0x12_3456, 0);

        assert!(ContractsStore::is_manifest_atomic_temporary_name(&manifest));
        assert!(!ContractsStore::is_manifest_atomic_temporary_name(
            &contract
        ));
    }

    #[test]
    fn maps_and_atomically_writes_generated_output_below_the_root() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts.create_dir_all().expect("contracts root");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let logical = CatalogPath::new("nested/main.yaml").expect("logical path");
        let destination = store
            .generated_leaf(&logical)
            .expect("validated destination");

        store
            .atomic_write(
                &destination,
                b"version: 1\n",
                &crate::context::ApplicationCancellation::new(),
            )
            .expect("atomic output");

        contracts.child("nested/main.yaml").assert("version: 1\n");
        let entries = std::fs::read_dir(contracts.child("nested").path())
            .expect("generated parent directory")
            .map(|entry| entry.expect("generated parent entry").file_name())
            .collect::<Vec<_>>();
        assert_eq!(entries, [std::ffi::OsString::from("main.yaml")]);
        let reserved = CatalogPath::new(".CONTRACT-KIT/output.yml").expect("reserved path");
        assert!(store.generated_leaf(&reserved).is_err());
        drop(destination);
        drop(store);
        temp.close().expect("close temporary root");
    }

    #[test]
    fn pre_canceled_atomic_write_preserves_destination_and_leaves_no_temporary() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts.create_dir_all().expect("contracts root");
        contracts
            .child("main.yml")
            .write_str("before\n")
            .expect("existing destination");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let destination = store
            .generated_leaf(&CatalogPath::new("main.yml").expect("logical destination"))
            .expect("generated destination");
        let cancellation = crate::context::ApplicationCancellation::new();
        cancellation.request();

        let error = store
            .atomic_write(&destination, b"after\n", &cancellation)
            .expect_err("pre-canceled write must not publish");

        assert!(matches!(error, CliError::OperationCanceled));
        contracts.child("main.yml").assert("before\n");
        let entries = std::fs::read_dir(contracts.path())
            .expect("contracts directory")
            .map(|entry| entry.expect("contracts entry").file_name())
            .collect::<Vec<_>>();
        assert_eq!(entries, [std::ffi::OsString::from("main.yml")]);

        drop(destination);
        drop(store);
        temp.close().expect("close temporary root");
    }

    #[test]
    fn cancellation_after_publication_open_aborts_and_removes_the_temporary() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts.create_dir_all().expect("contracts root");
        contracts
            .child("main.yml")
            .write_str("before\n")
            .expect("existing destination");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let destination = store
            .generated_leaf(&CatalogPath::new("main.yml").expect("logical destination"))
            .expect("generated destination");
        let temporary = std::ffi::OsString::from(".publication-canceled.tmp");
        let publication =
            ContractPublication::open(&destination, temporary.clone()).expect("opened publication");
        let cancellation = crate::context::ApplicationCancellation::new();
        cancellation.request();

        let error = publication
            .publish(b"after\n", &cancellation)
            .expect_err("cancellation after open must abort publication");

        assert!(matches!(error, CliError::OperationCanceled));
        contracts.child("main.yml").assert("before\n");
        contracts
            .child(std::path::Path::new(&temporary))
            .assert(predicates::path::missing());
        drop(destination);
        drop(store);
        temp.close().expect("close temporary root");
    }

    #[test]
    fn failed_destination_rename_aborts_and_removes_the_temporary() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts
            .child("main.yml")
            .create_dir_all()
            .expect("directory at destination name");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let destination = store
            .generated_leaf(&CatalogPath::new("main.yml").expect("logical destination"))
            .expect("generated destination");

        store
            .atomic_write(
                &destination,
                b"generated\n",
                &crate::context::ApplicationCancellation::new(),
            )
            .expect_err("a file cannot replace the destination directory");

        let entries = std::fs::read_dir(contracts.path())
            .expect("contracts directory")
            .map(|entry| entry.expect("contracts entry").file_name())
            .collect::<Vec<_>>();
        assert_eq!(entries, [std::ffi::OsString::from("main.yml")]);
        contracts
            .child("main.yml")
            .assert(predicates::path::is_dir());
        drop(destination);
        drop(store);
        temp.close().expect("close temporary root");
    }

    #[test]
    fn dropping_an_unfinished_publication_performs_best_effort_cleanup() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts.create_dir_all().expect("contracts root");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let destination = store
            .generated_leaf(&CatalogPath::new("main.yml").expect("logical destination"))
            .expect("generated destination");
        let temporary = std::ffi::OsString::from(".publication-drop.tmp");

        let publication =
            ContractPublication::open(&destination, temporary.clone()).expect("opened publication");
        contracts
            .child(std::path::Path::new(&temporary))
            .assert(predicates::path::exists());
        drop(publication);

        contracts
            .child(std::path::Path::new(&temporary))
            .assert(predicates::path::missing());
        drop(destination);
        drop(store);
        temp.close().expect("close temporary root");
    }

    #[cfg(unix)]
    #[test]
    fn explicit_abort_reports_atomic_temporary_cleanup_failure() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts.create_dir_all().expect("contracts root");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let destination = store
            .generated_leaf(&CatalogPath::new("main.yml").expect("logical destination"))
            .expect("generated destination");
        let temporary = std::ffi::OsString::from(".publication-cleanup.tmp");
        let publication =
            ContractPublication::open(&destination, temporary.clone()).expect("opened publication");
        let temporary_path = contracts.child(std::path::Path::new(&temporary));
        let parked = contracts.child("parked-temporary");
        std::fs::rename(temporary_path.path(), parked.path()).expect("park open temporary");
        temporary_path
            .create_dir_all()
            .expect("replace temporary with directory");

        let error = publication.abort(CliError::OperationCanceled);

        assert!(
            error
                .to_string()
                .contains("operation canceled; atomic temporary cleanup also failed"),
            "{error}"
        );
        temporary_path.assert(predicates::path::is_dir());
        parked.assert(predicates::path::exists());
        drop(destination);
        drop(store);
        temp.close().expect("close temporary root");
    }

    #[cfg(unix)]
    #[test]
    fn atomic_write_uses_the_anchored_contracts_root_after_replacement() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        let anchored = temp.child("anchored contracts");
        contracts.create_dir_all().expect("contracts root");
        contracts
            .child("existing.yml")
            .write_str("before\n")
            .expect("existing contract");
        let store = ContractsStore::new(contracts.path().to_path_buf());
        let cancellation = crate::context::ApplicationCancellation::new();
        let mut budget = store.limits.begin(&cancellation);
        store
            .read_with_budget(&mut budget)
            .expect("reading anchors the contracts root");

        std::fs::rename(contracts.path(), anchored.path()).expect("rename anchored root");
        contracts
            .create_dir_all()
            .expect("replacement contracts root");
        let destination = store
            .generated_leaf(&CatalogPath::new("nested/main.yml").expect("logical path"))
            .expect("anchored generated leaf");
        store
            .atomic_write(
                &destination,
                b"anchored\n",
                &crate::context::ApplicationCancellation::new(),
            )
            .expect("capability-relative atomic write");

        anchored.child("nested/main.yml").assert("anchored\n");
        contracts
            .child("nested/main.yml")
            .assert(predicates::path::missing());
        temp.close().expect("close temporary root");
    }

    #[test]
    fn reconciliation_leaf_reads_accept_the_exact_limit_and_reject_one_more_byte() {
        let exact = assert_fs::TempDir::new().expect("exact temporary root");
        let exact_contracts = exact.child("contracts");
        exact_contracts
            .child("main.yml")
            .write_binary(b"four")
            .expect("exact-size generated output");
        let exact_store = ContractsStore::new(exact_contracts.path().to_path_buf())
            .with_limits(CatalogReadLimits::new(1, 4, 4));
        let exact_leaf = exact_store
            .generated_leaf(&CatalogPath::new("main.yml").expect("exact logical path"))
            .expect("exact generated leaf");
        let mut exact_budget =
            exact_store.begin_reconciliation_read(&crate::context::ApplicationCancellation::new());
        let exact_snapshot = exact_store
            .read_leaf(&exact_leaf, &mut exact_budget)
            .expect("exact-size read")
            .expect("exact-size output exists");
        assert_eq!(exact_snapshot.bytes(), b"four");

        let excessive = assert_fs::TempDir::new().expect("excessive temporary root");
        let excessive_contracts = excessive.child("contracts");
        excessive_contracts
            .child("main.yml")
            .write_binary(b"five!")
            .expect("oversized generated output");
        let excessive_store = ContractsStore::new(excessive_contracts.path().to_path_buf())
            .with_limits(CatalogReadLimits::new(1, 4, 4));
        let excessive_leaf = excessive_store
            .generated_leaf(&CatalogPath::new("main.yml").expect("excessive logical path"))
            .expect("excessive generated leaf");
        let mut excessive_budget = excessive_store
            .begin_reconciliation_read(&crate::context::ApplicationCancellation::new());
        let error = excessive_store
            .read_leaf(&excessive_leaf, &mut excessive_budget)
            .expect_err("one byte beyond the file limit must fail");
        let CliError::CatalogReadLimit(error) = error else {
            panic!("expected typed file-byte limit")
        };
        assert_eq!(error.resource, CatalogReadLimitResource::FileBytes);
        assert_eq!(error.limit, 4);
        assert_eq!(error.observed_at_least, 5);
        assert_eq!(error.path, excessive_contracts.child("main.yml").path());

        drop(exact_snapshot);
        drop(exact_leaf);
        drop(exact_store);
        drop(excessive_leaf);
        drop(excessive_store);
        exact.close().expect("close exact temporary root");
        excessive.close().expect("close excessive temporary root");
    }

    #[cfg(unix)]
    #[test]
    fn generated_leaves_reject_symlink_ancestors_and_final_entries() {
        use std::os::unix::fs::symlink;

        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        let outside = temp.child("outside");
        contracts.create_dir_all().expect("contracts root");
        outside.create_dir_all().expect("outside directory");
        outside
            .child("external.yml")
            .write_binary(b"outside\n")
            .expect("outside file");
        symlink(outside.path(), contracts.child("linked").path()).expect("ancestor symlink");
        symlink(
            outside.child("external.yml").path(),
            contracts.child("linked.yml").path(),
        )
        .expect("final symlink");
        let store = ContractsStore::new(contracts.path().to_path_buf());

        let ancestor_error = store
            .generated_leaf(&CatalogPath::new("linked/main.yml").expect("ancestor logical path"))
            .expect_err("a generated ancestor symlink must fail");
        assert!(ancestor_error.to_string().contains("symbolic link"));

        let final_leaf = store
            .generated_leaf(&CatalogPath::new("linked.yml").expect("final logical path"))
            .expect("final-name leaf");
        let mut budget =
            store.begin_reconciliation_read(&crate::context::ApplicationCancellation::new());
        let final_error = store
            .read_leaf(&final_leaf, &mut budget)
            .expect_err("a generated final symlink must fail");
        assert!(final_error.to_string().contains("symbolic link"));

        temp.close().expect("close temporary root");
    }

    #[cfg(unix)]
    #[test]
    fn contract_reads_do_not_follow_or_insert_descendant_symlinks() {
        use std::os::unix::fs::symlink;

        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        let outside = temp.child("outside");
        contracts.create_dir_all().expect("contracts root");
        outside.create_dir_all().expect("outside root");
        contracts
            .child("main.yml")
            .write_str("root: ../src\n")
            .expect("contract document");
        outside
            .child("secret.yml")
            .write_str("outside\n")
            .expect("outside file");
        symlink(outside.path(), contracts.child("linked-directory").path())
            .expect("directory symlink");
        symlink(
            outside.child("secret.yml").path(),
            contracts.child("linked-file.yml").path(),
        )
        .expect("file symlink");

        let store = ContractsStore::new(contracts.path().to_path_buf());
        let cancellation = crate::context::ApplicationCancellation::new();
        let mut budget = store.limits.begin(&cancellation);
        let catalog = store
            .read_with_budget(&mut budget)
            .expect("contracts catalog");

        assert_eq!(catalog.len(), 1);
        assert!(
            catalog
                .get(&CatalogPath::new("main.yml").expect("document path"))
                .is_some()
        );
        temp.close().expect("close temporary root");
    }

    #[cfg(unix)]
    #[test]
    fn optional_read_accepts_a_directory_root_symlink_but_not_a_dangling_symlink() {
        use std::os::unix::fs::symlink;

        let temp = assert_fs::TempDir::new().expect("temporary root");
        let actual = temp.child("actual");
        actual.create_dir_all().expect("actual contracts root");
        actual
            .child("main.yml")
            .write_str("root: ../src\n")
            .expect("contract entry");
        let selected = temp.child("selected");
        symlink(actual.path(), selected.path()).expect("directory root symlink");
        let selected_store = ContractsStore::new(selected.path().to_path_buf());
        let cancellation = crate::context::ApplicationCancellation::new();
        let mut budget = selected_store.limits.begin(&cancellation);
        assert_eq!(
            selected_store
                .read_optional_with_budget(&mut budget)
                .expect("directory root symlink")
                .len(),
            1
        );

        let dangling = temp.child("dangling");
        symlink(temp.child("absent").path(), dangling.path()).expect("dangling root symlink");
        let dangling_store = ContractsStore::new(dangling.path().to_path_buf());
        let mut budget = dangling_store.limits.begin(&cancellation);
        assert!(
            dangling_store
                .read_optional_with_budget(&mut budget)
                .is_err(),
            "only a lexically absent root is optional"
        );
        temp.close().expect("close temporary root");
    }

    #[test]
    fn generated_contracts_move_the_baseline_and_completed_documents() {
        let baseline_path = CatalogPath::new("before.yml").expect("baseline path");
        let document_path = CatalogPath::new("main.yml").expect("document path");
        let mut baseline = FileCatalog::new();
        baseline
            .insert(baseline_path.clone(), b"before\n".to_vec())
            .expect("baseline insert");
        let mut documents = FileCatalog::new();
        documents
            .insert(document_path.clone(), b"after\n".to_vec())
            .expect("document insert");

        let (baseline, documents) = GeneratedContracts::new(baseline, documents).into_parts();

        assert_eq!(baseline.get(&baseline_path), Some(b"before\n".as_slice()));
        assert_eq!(documents.get(&document_path), Some(b"after\n".as_slice()));
    }

    #[test]
    fn contract_reads_enforce_entry_file_and_total_limits_in_path_order() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts.create_dir_all().expect("contracts root");
        contracts
            .child("a.yml")
            .write_binary(b"aaa")
            .expect("a contract");
        contracts
            .child("b.yml")
            .write_binary(b"bbb")
            .expect("b contract");

        let entry_store = ContractsStore::new(contracts.path().to_path_buf())
            .with_limits(CatalogReadLimits::new(1, 64, 64));
        let cancellation = crate::context::ApplicationCancellation::new();
        let mut budget = entry_store.limits.begin(&cancellation);
        let entry_error = entry_store
            .read_with_budget(&mut budget)
            .expect_err("the second sorted contract must exceed the entry budget");
        let CliError::CatalogReadLimit(entry_error) = entry_error else {
            panic!("expected typed entry limit")
        };
        assert_eq!(entry_error.resource, CatalogReadLimitResource::EntryCount);
        assert_eq!(entry_error.observed_at_least, 2);
        assert_eq!(entry_error.path, contracts.child("b.yml").path());

        let file_store = ContractsStore::new(contracts.path().to_path_buf())
            .with_limits(CatalogReadLimits::new(2, 64, 2));
        let mut budget = file_store.limits.begin(&cancellation);
        let file_error = file_store
            .read_with_budget(&mut budget)
            .expect_err("the first sorted contract must exceed per-file bytes");
        let CliError::CatalogReadLimit(file_error) = file_error else {
            panic!("expected typed file-byte limit")
        };
        assert_eq!(file_error.resource, CatalogReadLimitResource::FileBytes);
        assert_eq!(file_error.observed_at_least, 3);
        assert_eq!(file_error.path, contracts.child("a.yml").path());

        let total_store = ContractsStore::new(contracts.path().to_path_buf())
            .with_limits(CatalogReadLimits::new(2, 5, 64));
        let mut budget = total_store.limits.begin(&cancellation);
        let total_error = total_store
            .read_with_budget(&mut budget)
            .expect_err("the second sorted contract must exceed total bytes");
        let CliError::CatalogReadLimit(total_error) = total_error else {
            panic!("expected typed total-byte limit")
        };
        assert_eq!(total_error.resource, CatalogReadLimitResource::TotalBytes);
        assert_eq!(total_error.limit, 5);
        assert_eq!(total_error.observed_at_least, 6);
        assert_eq!(total_error.path, contracts.child("b.yml").path());
        temp.close().expect("close temporary root");
    }

    #[test]
    fn reserved_metadata_does_not_consume_contract_catalog_budgets() {
        let temp = assert_fs::TempDir::new().expect("temporary root");
        let contracts = temp.child("contracts");
        contracts
            .child(".contract-kit")
            .create_dir_all()
            .expect("metadata directory");
        contracts
            .child(".contract-kit/generated-files.json")
            .write_binary(&[b'x'; 128])
            .expect("large metadata file");
        contracts
            .child("main.yml")
            .write_binary(b"four")
            .expect("contract document");

        let store = ContractsStore::new(contracts.path().to_path_buf())
            .with_limits(CatalogReadLimits::new(1, 4, 4));
        let cancellation = crate::context::ApplicationCancellation::new();
        let mut budget = store.limits.begin(&cancellation);
        let catalog = store
            .read_with_budget(&mut budget)
            .expect("reserved metadata is outside the contract catalog budget");

        assert_eq!(catalog.len(), 1);
        assert_eq!(
            catalog.get(&CatalogPath::new("main.yml").expect("document path")),
            Some(&b"four"[..])
        );
        temp.close().expect("close temporary root");
    }
}
